version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: test-db-docker
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: 13821382
      POSTGRES_DB: test_db_docker
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8000:8000"
